[tool.poetry]
name = "podcast-archiver"
version = "0.4.0"
description = "Archive all episodes from your favorite podcasts"
authors = ["Jan Willhaus <mail@janwillhaus.de>"]
license = "MIT"
readme = "README.md"
packages = [{ include = "podcast_archiver.py" }]

[tool.poetry.dependencies]
python = "^3.9"
python-dateutil = "^2.8.2"
feedparser = "^6.0.10"


[tool.poetry.group.dev.dependencies]
ruff = "^0.0.262"
black = "^23.3.0"


[tool.ruff]
line-length = 120
target-version = "py39"


[tool.black]
line-length = 120
target-version = ['py39', 'py310', 'py311']


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
